name: Cross-repo Issue Creation

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  cross-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.XREPO_APP_ID }}
          private_key: ${{ secrets.XREPO_SECRET }}
      - name: create issue in other repo
        if: "!contains(github.event.pull_request.labels.*.name, 'do not port') && github.event.pull_request.merged"
        run: |
          curl -X "POST" "https://api.github.com/repos/bretg/test2/issues?state=all" \
             -H "Cookie: logged_in=no" \
             -u ${{ steps.generate_token.outputs.token }} \
             -H "Content-Type: text/plain; charset=utf-8" \
             -d $'{
               "title": "New PR in Test1: ${{ github.event.pull_request.title }}",
               "body": "A PR was merged over on test 1\\n\\n- [https://github.com/bretg/test1/pull/${{github.event.number}}](https://github.com/bretg/test1/pull/${{github.event.number}})\\n- timestamp: ${{ github.event.pull_request.merged_at}}",
               "labels": [ "auto" ]
            }'
