name: Cross-repo Issue Creation

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  cross-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.XREPO_APP_ID }}
          private_key: ${{ secrets.XREPO_PEM }}
      - name: create issue in other repo
        if: "!contains(github.event.pull_request.labels.*.name, 'do not port') && github.event.pull_request.merged"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh issue create --repo bretg/test2 --title "New PR in test1: ${{ github.event.pull_request.title }}" \
              --body "A PR was merged over on test 1\\n\\n- [https://github.com/bretg/test1/pull/${{github.event.number}}](https://github.com/bretg/test1/pull/${{github.event.number}})\\n- timestamp: ${{ github.event.pull_request.merged_at}}"
              --label auto
